homework_10/blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("main.urls", namespace="main")),
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
]

homework_10/blog/main/urls.py
from django.urls import path
from .views import (
    index,
    AuthorsList,
    AuthorsDetail,
    AuthorsCreate,
    PostsList,
    PostsDetail,
    PostsCreate,
    PostsUpdate,
    PostsDelete,
)

app_name = "main"

urlpatterns = [
    path("", index, name="home_page"),
    path("authors/", AuthorsList.as_view(), name="authors"),
    path("authors/add_author/", AuthorsCreate.as_view(), name='add_author'),
    path("authors/<slug:pk>/", AuthorsDetail.as_view(), name="author"),
    path("posts/", PostsList.as_view(), name="posts"),
    path("posts/<int:pk>/edit/", PostsUpdate.as_view(), name="edit"),
    path("posts/<int:pk>/delete/", PostsDelete.as_view(), name="delete"),
    path("posts/add/", PostsCreate.as_view(), name="add_post"),
    path("posts/<slug:pk>/", PostsDetail.as_view(), name="post"),
]

homework_10/blog/main/models.py
from django.db import models


# Create your models here.


class Author(models.Model):
    name = models.CharField(max_length=64)
    username = models.CharField(max_length=64, unique=True)
    email = models.CharField(max_length=120, blank=True, null=True)

    def __str__(self):
        return f"Author: name={self.name!r}, username={self.username!r}, email={self.email!r}"

    def __repr__(self):
        return str(self)

    # class Meta:
    #     ordering = ['username']


class Post(models.Model):
    title = models.CharField(max_length=64, unique=True)
    body = models.TextField(blank=True, null=True)
    author_id = models.ForeignKey(
        Author,
        on_delete=models.PROTECT,
    )

    def __str__(self):
        return f"Post: title={self.title!r}, body={self.body!r}"

    def __repr__(self):
        return str(self)

homework_10/blog/main/forms.py
# from django import forms
from django.forms import ModelForm

from .models import Author, Post


class AuthorCreateForm(ModelForm):
    class Meta:
        model = Author
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for _, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"


class PostCreateForm(ModelForm):
    class Meta:
        model = Post
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for _, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"

homework_10/blog/main/views.py
from typing import Any

from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)

from .forms import AuthorCreateForm, PostCreateForm
from .models import Author, Post


# Create your views here.


def index(request: HttpRequest) -> HttpResponse:
    return render(
        request=request,
        template_name="main/index.html",
    )


class AuthorsList(ListView):
    model = Author

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['title'] = "Authors list"
        return context


class AuthorsDetail(DetailView):
    model = Author

    def get_context_data(self, **kwargs: Any):
        context = super().get_context_data(**kwargs)
        context['posts'] = Post.objects.filter(author_id=self.object.pk)
        return context


class AuthorsCreate(CreateView):
    model = Author
    # fields = '__all__'
    form_class = AuthorCreateForm
    success_url = reverse_lazy('main:authors')


class PostsList(ListView):
    model = Post

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['posts_list'] = "Posts list"
        context['title'] = "Posts list"
        return context


class PostsDetail(DetailView):
    model = Post

    def get_context_data(self, **kwargs: Any):
        context = super().get_context_data(**kwargs)
        return context


class PostsCreate(CreateView):
    model = Post
    form_class = PostCreateForm
    success_url = reverse_lazy('main:posts')


class PostsUpdate(UpdateView):
    model = Post
    template_name = 'main/post_form_edit.html'
    form_class = PostCreateForm
    success_url = reverse_lazy('main:posts')


class PostsDelete(DeleteView):
    model = Post
    success_url = reverse_lazy('main:posts')

homework_10/blog/main/templates/main/author_detail.html
{% extends 'root.html' %} {% block title %} User: {{ author.name}} {% endblock %}
{% block body %}
<h2>User: {{author.name}}</h2>

<div>
  <div>
    <div>name: {{ author.name }}</div>
    <div>username: {{ author.username }}</div>
    <div>
      email: {% if author.email != None %} {{author.email}} {% endif %}
    </div>
  </div>
</div>
<div class="grid">
  <h3>Posts author {{author.name}}</h3>
  <ul class="list-group">
    {% for post in posts %}
    <li class="list-group-item m-0">
      title: <a href="{% url 'main:post' post.pk %}">{{ post.title }}</a>
    </li>
    {% endfor %}
  </ul>
</div>
<div class="my-2">
  <a class="btn btn-primary" href="{% url 'main:authors' %}">Back to authors list</a>
</div>
{% endblock %}

homework_10/blog/main/templates/main/author_form.html
{% extends 'root.html' %}

{% block title %}
    {{ page_title }}
{% endblock %}

{% block body %}
    <h2>User create</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="create">
    </form>
    <a href="{% url 'main:authors' %}">Back to list</a>

{% endblock %}

homework_10/blog/main/templates/main/author_list.html
{% extends 'root.html' %} 
{% block title %} 
{{ title }} 
{% endblock %} 

{% block body%}
<h2>Authors list</h2>
<ul>
  {% for author in author_list %}
  <li>
    name: {{ author.name }}
    <a href="{% url 'main:author' author.id %}">{{ author.name }}</a>;
    username: {{author.username }}
  </li>
  {% endfor %}
</ul>
<div class="my-2">
  <a class="btn btn-primary" href="{% url 'main:add_author' %}">Add author</a>
</div>
{% endblock %}

homework_10/blog/main/templates/main/index.html
{% extends 'root.html' %} 
{% block title %} Home page {% endblock title %} 
{% block body %}
<h1>Blog</h1>
<div>
  <ul>
    This is a blog project:
    <li>
      authors with a link to details
      <a href="{% url 'main:authors' %}"> authors list </a>
    </li>
    <li>posts with a link to <a href="{% url 'main:posts' %}">posts list</a></li>
  </ul>
</div>
{% endblock body %}

homework_10/blog/main/templates/main/post_confirm_delete.html
{% extends 'root.html' %}
{% block title %}
Delete zodiac
{% endblock title %}

{% block body %}
<h1>Delete post</h1>
<form action="" method="post">{% csrf_token %}
      <p>Are you sure you want to delete "{{ post.title }}"?</p>
      <input type="submit" value="Confirm" />
</form>



<div>
  <a href="{% url 'main:posts' %}">Back to posts list</a>
</div>
{% endblock body %}

homework_10/blog/main/templates/main/post_detail.html
{% extends 'root.html' %} {% block title %} Post: {{ post.pk}} {% endblock %} 
{% block body %}
<h2>Post: {{post.title}}</h2>

<div>
  <div>
    <div>title: {{ post.title }}</div>
    <div>body: {% if post.body != None %} {{ post.body}} {% endif %}</div>
    <div>
      username:
      <a href="{% url 'main:author' post.author_id.pk %}">
        {{ post.author_id.username}}
      </a>
    </div>
  </div>

  <div class="my-2">
  <a class="btn btn-success" href="{% url 'main:posts' %}">Back to posts list</a>
  <a class="btn btn-primary" href="{% url 'main:edit' post.pk %}">Edit post</a>
  <a class="btn btn-danger" href="{% url 'main:delete' post.pk %}">Delete post</a>


</div>
  {% endblock %}

homework_10/blog/main/templates/main/post_form.html
{% extends 'root.html' %}

{% block title %}
    {{ page_title }}
{% endblock %}

{% block body %}
    <h2>Post create</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="create">
    </form>
    <a href="{% url 'main:posts' %}">Back to list</a>

{% endblock %}

homework_10/blog/main/templates/main/post_form_edit.html
{% extends 'root.html' %}

{% block title %}
    {{ page_title }}
{% endblock %}

{% block body %}
    <h2>Post create</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="update">
    </form>
    <a href="{% url 'main:posts' %}">Back to list</a>

{% endblock %}

homework_10/blog/main/templates/main/post_list.html
{% extends 'root.html' %} 
{% block title %} Posts {% endblock %}

 {% block body%}
<h2>Posts list</h2>

<ul>
  {% for post in post_list %}
  <li>
    title: <a href="{% url 'main:post' post.pk %}">{{ post.title }}</a>;

    author: 
    <a href="{% url 'main:author' post.author_id.pk %}">{{ post.author_id.username }}</a>

  </li>
  {% endfor %}
</ul>
<div class="my-2">
  <a class="btn btn-primary" href="{% url 'main:add_post' %}">Add post</a>
</div>
{% endblock%}

homework_10/blog/templates/root.html
<!DOCTYPE html>
{% load  static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}" />
  </head>

  <body class="m-2">
    <nav class="navbar navbar-expand-md bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Blog</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbar-content"
          aria-controls="navbar-content"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar-content">
          <ul class="navbar-nav me-auto">       
            <li class="nav-item">
              <a href="/" class="nav-link"> Home page</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'main:authors' %}" class="nav-link"> Authors list</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'main:posts' %}" class="nav-link"> Posts list</a>
            </li> 
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <div>
        {% for category, message in messages %}
        <div
          {% comment %}
          class="alert alert-{{ 'primary' if category == 'message' else category }}"
          {% endcomment %}
        >
          {{ message }}
        </div>
        {% endfor %}
      </div>

    </div>
    {% block body %} {% endblock %}
    <footer>
      {% block footer %}{%  endblock %}
       <p> &copy otus-python-basic_2023-05, safarov-ar@yandex.ru </p>
    </footer>
    <script src="{% static 'js/bootstrap.bundle.min.js'%}"></script>
  </body>
</html>